"use strict";
let num3 = 10;
let num4 = 5;
let num5;
num5 = num3 + num4;
console.log("Tổng:", num5);
num5 = num3 - num4;
console.log("Hiệu:", num5);
num5;
num5 = num3 * num4;
console.log("Tích:", num5);
num5 = num3 / num4;
console.log("Thương:", num5);
// Thay đổi kiểu dữ liệu number thành boolean
num3 = "10";
num4 = true;
num5 = num3 + num4;
console.log("Kết quả sau khi thay đổi kiểu dữ liệu:");
console.log("Tổng:", num5);
num5 = num3 - num4;
console.log("Hiệu:", num5);
num5 = num3 * num4;
console.log("Tích:", num5);
num5 = num3 / num4;
console.log("Thương:", num5);
